// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: diaoduBigCmd.proto

package santint_diaodu_big_cmd;

public final class DiaoduBigCmd {
  private DiaoduBigCmd() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code santint_diaodu_big_cmd.CMD_NUM}
   */
  public enum CMD_NUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>chaocai_cmd = 1;</code>
     *
     * <pre>
     *炒菜客户端
     * </pre>
     */
    chaocai_cmd(0, 1),
    /**
     * <code>coldDish_cmd = 13;</code>
     *
     * <pre>
     *凉菜客户端
     * </pre>
     */
    coldDish_cmd(1, 13),
    /**
     * <code>passDishes_cmd = 14;</code>
     *
     * <pre>
     *传菜客户端
     * </pre>
     */
    passDishes_cmd(2, 14),
    /**
     * <code>burden_cmd = 15;</code>
     *
     * <pre>
     *打荷客户端
     * </pre>
     */
    burden_cmd(3, 15),
    ;

    /**
     * <code>chaocai_cmd = 1;</code>
     *
     * <pre>
     *炒菜客户端
     * </pre>
     */
    public static final int chaocai_cmd_VALUE = 1;
    /**
     * <code>coldDish_cmd = 13;</code>
     *
     * <pre>
     *凉菜客户端
     * </pre>
     */
    public static final int coldDish_cmd_VALUE = 13;
    /**
     * <code>passDishes_cmd = 14;</code>
     *
     * <pre>
     *传菜客户端
     * </pre>
     */
    public static final int passDishes_cmd_VALUE = 14;
    /**
     * <code>burden_cmd = 15;</code>
     *
     * <pre>
     *打荷客户端
     * </pre>
     */
    public static final int burden_cmd_VALUE = 15;


    public final int getNumber() { return value; }

    public static CMD_NUM valueOf(int value) {
      switch (value) {
        case 1: return chaocai_cmd;
        case 13: return coldDish_cmd;
        case 14: return passDishes_cmd;
        case 15: return burden_cmd;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CMD_NUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<CMD_NUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CMD_NUM>() {
            public CMD_NUM findValueByNumber(int number) {
              return CMD_NUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return DiaoduBigCmd.getDescriptor().getEnumTypes().get(0);
    }

    private static final CMD_NUM[] VALUES = values();

    public static CMD_NUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    CMD_NUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:santint_diaodu_big_cmd.CMD_NUM)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022diaoduBigCmd.proto\022\026santint_diaodu_big" +
      "_cmd*P\n\007CMD_NUM\022\017\n\013chaocai_cmd\020\001\022\020\n\014cold" +
      "Dish_cmd\020\r\022\022\n\016passDishes_cmd\020\016\022\016\n\nburden" +
      "_cmd\020\017"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
